name: Deploy Documentation

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install MkDocs
      run: |
        pip install mkdocs

    - name: Install Lua and LuaRocks
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.3 lua5.3-dev
        curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
        tar zxf lua-5.3.5.tar.gz
        cd lua-5.3.5
        make linux test
        sudo make install
        cd ..
        curl -R -O https://luarocks.org/releases/luarocks-3.8.0.tar.gz
        tar zxpf luarocks-3.8.0.tar.gz
        cd luarocks-3.8.0
        ./configure --with-lua-include=/usr/local/include
        make
        sudo make install
        cd ..

    - name: Install LDoc
      run: |
        luarocks install ldoc --local
        export PATH=$HOME/.luarocks/bin:$PATH

    - name: Generate LDoc Documentation
      run: |
        mkdir -p site/docs
        ~/.luarocks/bin/ldoc -d site/docs src

    - name: Create MkDocs configuration
      run: |
        echo "site_name: My Project Documentation" > mkdocs.yml
        echo "nav:" >> mkdocs.yml
        echo "  - Home: index.md" >> mkdocs.yml
        echo "  - Documentation:" >> mkdocs.yml
        echo "      - Reference: docs/index.html" >> mkdocs.yml
        echo "theme:" >> mkdocs.yml
        echo "  name: readthedocs" >> mkdocs.yml

    - name: Build MkDocs Site
      run: |
        mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
