name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: '5.3'  # Specify the Lua version you need

      - name: Install LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks

      - name: Install LDoc
        run: |
          luarocks install ldoc

      - name: Generate documentation
        run: |
          ldoc .  # Adjust this if you need to specify a different directory or configuration file
        id: generate_docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Specify the directory where LDoc generates the documentation
