name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install MkDocs
      run: |
        pip install mkdocs

    - name: Install LuaRocks and LDoc
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        luarocks install ldoc

    - name: Generate LDoc Documentation
      run: |
        mkdir -p site/docs
        ldoc -d site/docs src

    - name: Create MkDocs configuration
      run: |
        echo "site_name: My Project Documentation" > mkdocs.yml
        echo "nav:" >> mkdocs.yml
        echo "  - Home: index.md" >> mkdocs.yml
        echo "  - Documentation:" >> mkdocs.yml
        echo "      - Reference: docs/index.html" >> mkdocs.yml
        echo "theme:" >> mkdocs.yml
        echo "  name: readthedocs" >> mkdocs.yml

    - name: Build MkDocs Site
      run: |
        mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
